# Generated by Django 2.1.5 on 2019-01-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribers',
            new_name='Subcriber',
        ),
    ]
