# Generated by Django 2.1.5 on 2019-02-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190130_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcriber',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
