# Generated by Django 2.1.5 on 2019-01-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190131_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
